linters:
  enable-all: true
  disable:
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag
    - varnamelen
    - revive
    - testpackage
    - testableexamples
    - exhaustruct
    - depguard
    - stylecheck

    # Deprecated ones:
    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
  exclude-dirs-use-default: false
